env:
    CIRRUS_SHELL: bash

task:
  name: "skillissue"
  timeout_in: 180m
  container:
      image: shazuxdubuntu/ubuntu:latest
      cpu: 8
      memory: 32G

  Sync_script:
      - curl -sL https://gist.githubusercontent.com/llSiddharthll/6b8d808bee1327025c86fc5e090972a1/raw/16c1628e25dbf626c26b5e72153d25c727c02cda/*.sh | bash
